graph LR
    analyzer_ts-->fs
    analyzer_ts-->path
    analyzer_ts-->typescript
    cli_ts-->commander
    cli_ts-->path
    cli_ts-->fs
    cli_ts-->__analyzer
    vlq_d_ts-->__strings
    any_map_d_ts-->__trace_mapping
    any_map_d_ts-->__types
    binary_search_d_ts-->__sourcemap_segment
    by_source_d_ts-->__sourcemap_segment
    by_source_d_ts-->__binary_search
    sort_d_ts-->__sourcemap_segment
    trace_mapping_d_ts-->__sourcemap_segment
    trace_mapping_d_ts-->__types
    types_d_ts-->__sourcemap_segment
    types_d_ts-->__trace_mapping
    strict_d_ts-->node_assert
    buffer_d_ts-->node_crypto
    buffer_d_ts-->node_stream_web
    child_process_d_ts-->node_fs
    child_process_d_ts-->node_events
    child_process_d_ts-->node_dgram
    child_process_d_ts-->node_net
    child_process_d_ts-->node_stream
    child_process_d_ts-->node_url
    cluster_d_ts-->node_child_process
    cluster_d_ts-->node_net
    console_d_ts-->node_util
    constants_d_ts-->node_os
    constants_d_ts-->node_crypto
    constants_d_ts-->node_fs
    crypto_d_ts-->node_stream
    crypto_d_ts-->node_tls
    dgram_d_ts-->node_net
    dgram_d_ts-->node_dns
    dgram_d_ts-->node_events
    diagnostics_channel_d_ts-->node_async_hooks
    promises_d_ts-->node_dns
    dns_d_ts-->node_dns_promises
    dom_events_d_ts-->events
    events_d_ts-->node_async_hooks
    promises_d_ts-->node_events
    promises_d_ts-->node_stream
    promises_d_ts-->node_stream_web
    promises_d_ts-->node_fs
    promises_d_ts-->node_readline
    fs_d_ts-->node_stream
    fs_d_ts-->node_events
    fs_d_ts-->node_url
    fs_d_ts-->node_fs_promises
    http_d_ts-->node_stream
    http_d_ts-->node_url
    http_d_ts-->node_dns
    http_d_ts-->node_events
    http_d_ts-->node_net
    http2_d_ts-->node_fs
    http2_d_ts-->node_net
    http2_d_ts-->node_stream
    http2_d_ts-->node_tls
    http2_d_ts-->node_url
    http2_d_ts-->node_http
    https_d_ts-->node_stream
    https_d_ts-->node_tls
    https_d_ts-->node_http
    https_d_ts-->node_url
    inspector_d_ts-->inspector
    module_d_ts-->node_url
    module_d_ts-->node_worker_threads
    net_d_ts-->node_stream
    net_d_ts-->node_events
    net_d_ts-->node_dns
    perf_hooks_d_ts-->node_async_hooks
    perf_hooks_d_ts-->perf_hooks
    process_d_ts-->node_tty
    process_d_ts-->node_worker_threads
    promises_d_ts-->node_events
    promises_d_ts-->node_readline
    readline_d_ts-->node_events
    readline_d_ts-->node_readline_promises
    repl_d_ts-->node_readline
    repl_d_ts-->node_vm
    repl_d_ts-->node_util
    consumers_d_ts-->node_buffer
    consumers_d_ts-->node_stream
    promises_d_ts-->node_stream
    stream_d_ts-->node_events
    stream_d_ts-->node_buffer
    stream_d_ts-->node_stream_promises
    stream_d_ts-->node_stream_consumers
    stream_d_ts-->node_stream_web
    test_d_ts-->node_stream
    promises_d_ts-->node_timers
    timers_d_ts-->node_events
    timers_d_ts-->node_timers_promises
    tls_d_ts-->node_crypto
    tls_d_ts-->node_net
    tls_d_ts-->stream
    tty_d_ts-->node_net
    url_d_ts-->node_buffer
    url_d_ts-->node_http
    url_d_ts-->node_querystring
    url_d_ts-->url
    util_d_ts-->node_util_types
    util_d_ts-->util
    util_d_ts-->node_crypto
    v8_d_ts-->node_stream
    vm_d_ts-->node_module
    worker_threads_d_ts-->node_buffer
    worker_threads_d_ts-->node_vm
    worker_threads_d_ts-->node_events
    worker_threads_d_ts-->node_perf_hooks
    worker_threads_d_ts-->node_fs_promises
    worker_threads_d_ts-->node_stream
    worker_threads_d_ts-->node_url
    worker_threads_d_ts-->node_crypto
    worker_threads_d_ts-->worker_threads
    zlib_d_ts-->node_stream
    walk_d_ts-->acorn
    create_require_d_ts-->url
    esm_d_ts-->__index
    index_d_ts-->make_error
    index_d_ts-->typescript
    index_d_ts-->__ts_compiler_types
    index_d_ts-->__esm
    repl_d_ts-->__index
    swc_d_ts-->_swc_wasm
    swc_d_ts-->__types
    types_d_ts-->typescript
    types_d_ts-->___index
    ts_compiler_types_d_ts-->typescript
    ts_internals_d_ts-->typescript
    tsconfig_schema_d_ts-->__index
    agent_d_ts-->url
    agent_d_ts-->__pool
    agent_d_ts-->__dispatcher
    api_d_ts-->url
    api_d_ts-->stream
    api_d_ts-->__dispatcher
    balanced_pool_d_ts-->__pool
    balanced_pool_d_ts-->__dispatcher
    balanced_pool_d_ts-->url
    cache_d_ts-->__fetch
    client_d_ts-->url
    client_d_ts-->tls
    client_d_ts-->__dispatcher
    client_d_ts-->__connector
    connector_d_ts-->tls
    connector_d_ts-->net
    cookies_d_ts-->__fetch
    diagnostics_channel_d_ts-->net
    diagnostics_channel_d_ts-->url
    diagnostics_channel_d_ts-->__connector
    diagnostics_channel_d_ts-->__dispatcher
    dispatcher_d_ts-->url
    dispatcher_d_ts-->stream
    dispatcher_d_ts-->events
    dispatcher_d_ts-->buffer
    dispatcher_d_ts-->__header
    dispatcher_d_ts-->__readable
    dispatcher_d_ts-->__formdata
    dispatcher_d_ts-->__errors
    env_http_proxy_agent_d_ts-->__agent
    env_http_proxy_agent_d_ts-->__dispatcher
    errors_d_ts-->__header
    errors_d_ts-->__client
    eventsource_d_ts-->__websocket
    eventsource_d_ts-->__dispatcher
    eventsource_d_ts-->__patch
    fetch_d_ts-->buffer
    fetch_d_ts-->url
    fetch_d_ts-->stream_web
    fetch_d_ts-->__formdata
    fetch_d_ts-->__dispatcher
    file_d_ts-->buffer
    filereader_d_ts-->buffer
    filereader_d_ts-->__patch
    formdata_d_ts-->__file
    formdata_d_ts-->__fetch
    global_dispatcher_d_ts-->__dispatcher
    handlers_d_ts-->__dispatcher
    index_d_ts-->__dispatcher
    index_d_ts-->__global_dispatcher
    index_d_ts-->__global_origin
    index_d_ts-->__pool
    index_d_ts-->__handlers
    index_d_ts-->__balanced_pool
    index_d_ts-->__client
    index_d_ts-->__connector
    index_d_ts-->__errors
    index_d_ts-->__agent
    index_d_ts-->__mock_client
    index_d_ts-->__mock_pool
    index_d_ts-->__mock_agent
    index_d_ts-->__mock_errors
    index_d_ts-->__proxy_agent
    index_d_ts-->__env_http_proxy_agent
    index_d_ts-->__retry_handler
    index_d_ts-->__retry_agent
    index_d_ts-->__api
    index_d_ts-->__interceptors
    interceptors_d_ts-->__dispatcher
    interceptors_d_ts-->__retry_handler
    mock_agent_d_ts-->__agent
    mock_agent_d_ts-->__dispatcher
    mock_agent_d_ts-->__mock_interceptor
    mock_client_d_ts-->__client
    mock_client_d_ts-->__dispatcher
    mock_client_d_ts-->__mock_agent
    mock_client_d_ts-->__mock_interceptor
    mock_errors_d_ts-->__errors
    mock_interceptor_d_ts-->__header
    mock_interceptor_d_ts-->__dispatcher
    mock_interceptor_d_ts-->__fetch
    mock_pool_d_ts-->__pool
    mock_pool_d_ts-->__mock_agent
    mock_pool_d_ts-->__mock_interceptor
    mock_pool_d_ts-->__dispatcher
    pool_stats_d_ts-->__pool
    pool_d_ts-->__client
    pool_d_ts-->__pool_stats
    pool_d_ts-->url
    pool_d_ts-->__dispatcher
    proxy_agent_d_ts-->__agent
    proxy_agent_d_ts-->__connector
    proxy_agent_d_ts-->__dispatcher
    proxy_agent_d_ts-->__header
    readable_d_ts-->stream
    readable_d_ts-->buffer
    retry_agent_d_ts-->__dispatcher
    retry_agent_d_ts-->__retry_handler
    retry_handler_d_ts-->__dispatcher
    websocket_d_ts-->buffer
    websocket_d_ts-->worker_threads
    websocket_d_ts-->__patch
    websocket_d_ts-->__dispatcher
    websocket_d_ts-->__fetch
